ToDoApp/ToDoApp/Models/CreateTask.cs
namespace ToDoApp.Models
{
    public class CreateTaskView
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime? deadline { get; set; }
        public int priority { get; set; }
        public int status { get; set; }

        public CreateTaskView() { }

        public CreateTaskView(string name, string description, DateTime? deadline, int priority, int status)
        {
            Name = name;
            Description = description;
            this.deadline = deadline;
            this.priority = priority;
            this.status = status;
        }
    }


}

ToDoApp/ToDoApp/Models/Error.cs
namespace ToDoApp.Models
{
    public class Error
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ToDoApp/ToDoApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using ToDoApp.Models;

namespace ToDoApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ToDoApp/ToDoApp/Controllers/TaskController.cs
using Microsoft.AspNetCore.Mvc;
using ToDoApp.Data;
using ToDoApp.Models;
using Task = ToDoApp.Data.Task;

namespace ToDoApp.Controllers
{

        public class TaskController : Controller
        {
            private readonly MyDbContext _context;

            public TaskController(MyDbContext context)
            {
                _context = context;
            }

            [HttpGet]
            public IActionResult Index()
            {
                var tasks = _context.tasks.ToList();
                return View(tasks);
            }

            [HttpGet]
            public IActionResult Create()
            {
                return View();
            }

            [HttpPost]
            public IActionResult Create(CreateTaskView task)
            {
                var tasks = new Task()
                {
                    Name= task.Name,
                    Description= task.Description,
                    deadline= task.deadline,
                    priority= task.priority,
                    status= task.status,
                };
                _context.tasks.Add(tasks);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            /*[HttpGet]
            public IActionResult View(int ID)
            {
                var task = _context.tasks.FirstOrDefault(x => x.ID == ID);
                if (task != null)
                {
                    var tasks = new ViewTask()
                    {
                        ID = task.ID,
                        NameTask = task.NameTask,
                        DescriptionTask = task.DescriptionTask,
                        Deadline = task.Deadline,
                        Priority = task.Priority,
                        StartupBase = task.StartupBase
                    };
                    return View("View", tasks);
                }
                return RedirectToAction("Index");
            }

            [HttpPost]
            public IActionResult View(ViewTask update)
            {
                var task = _context.tasks.Find(update.ID);
                if (task != null)
                {
                    task.NameTask = update.NameTask;
                    task.DescriptionTask = update.DescriptionTask;
                    task.NameTask = update.NameTask;
                    task.Deadline = update.Deadline;
                    task.Priority = update.Priority;
                    task.StartupBase = update.StartupBase;
                    _context.SaveChanges();
                    return RedirectToAction("Index");
                }
                return RedirectToAction("Index");
            }

            [HttpPost]
            public IActionResult Delete(ViewTask update)
            {
                var task = _context.tasks.Find(update.ID);
                if (task != null)
                {
                    _context.tasks.Remove(task);
                    _context.SaveChanges();

                }
                return RedirectToAction("Index");
            }

            [HttpGet]
            public IActionResult Search(string name)
            {
                var task = _context.tasks.Find(name);
                if (task != null)
                {
                    return RedirectToAction("Index", task);
                }
                return RedirectToAction("Index");
            }
        }*/


    }
}

ToDoApp/ToDoApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div>
    <h1>TASKS LIST</h1>
    <a class="nav-link text-dark" asp-area="" asp-controller="Task" asp-action="Index">List Task</a>
</div>

ToDoApp/ToDoApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ToDoApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ToDoApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Task" asp-action="Create">Create</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ToDoApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ToDoApp/ToDoApp/Views/Task/Create.cshtml
@model ToDoApp.Models.CreateTask
@{
}

<h1>Create Task</h1>
Task Name<br />
<input type="text" class="form-control" asp-for="Name"><br />
Task Description<br />
<input type="text" class="form-control" asp-for="Description"><br />
Deadline<br />
<input type="date" class="form-control" asp-for="deadline"><br />
Priority<br />
<input type="text" class="form-control" asp-for="priority"><br />
Status<br />
<input type="text" class="form-control" asp-for="status"><br />
<input type="submit" class="btn btn-primary" asp-action="Submit"/>

ToDoApp/ToDoApp/Views/Task/Index.cshtml
@model List<ToDoApp.Data.Task>
@{
}

<h1>List Task</h1>
<table class="table">
    <a class="nav-link text-dark" asp-area="" asp-controller="Create" asp-action="Index">Create new task</a> 
    <thead>
        <tr>
            <th>Task Name</th>
            <th>Task Description</th>
            <th>Deadline</th>
            <th>Priority</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var task in Model)
        {
            <tr>
                <td>@task.Name</td>
                <td>@task.Description</td>
                <td>@task.deadline</td>
                <td>@task.priority</td>
                <td>@task.status</td>
            </tr>
        }
    </tbody>
</table>